#Requires -Version 5.1
<#
.SYNOPSIS
  Scan VSTplugin asset root and generate Inno include files.
.DESCRIPTION
  Writes generated\files.inc and generated\run.inc for glbwl.iss.
  Dedup: same plugin file name under Program Files vs Plugins keeps Program Files.
#>
param(
    [string]$AssetRoot = '',
    [string]$ProjectRoot = $PSScriptRoot
)

$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

function Get-DefaultAssetRoot {
    # D:\调音资产\VSTplugin
    $folder = -join @([char]0x8C03, [char]0x97F3, [char]0x8D44, [char]0x4EA7)
    return (Join-Path (Join-Path 'D:\' $folder) 'VSTplugin')
}

function Get-RegDirName {
    # 注册表
    return (-join @([char]0x6CE8, [char]0x518C, [char]0x8868))
}

if ([string]::IsNullOrWhiteSpace($AssetRoot)) {
    $AssetRoot = Get-DefaultAssetRoot
}

$outDir = Join-Path $ProjectRoot 'generated'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$filesInc = Join-Path $outDir 'files.inc'
$runInc = Join-Path $outDir 'run.inc'

function Get-RelPath([string]$Full, [string]$Root) {
    $fullNorm = [System.IO.Path]::GetFullPath($Full)
    $rootNorm = [System.IO.Path]::GetFullPath($Root).TrimEnd('\')
    if (-not $fullNorm.StartsWith($rootNorm, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Path not under root: $Full"
    }
    return $fullNorm.Substring($rootNorm.Length).TrimStart('\')
}

function Escape-InnoPath([string]$Path) {
    return $Path.Replace('"', '')
}

if (-not (Test-Path -LiteralPath $AssetRoot)) {
    Write-Error "Asset root not found: $AssetRoot"
}

$assetRootFull = [System.IO.Path]::GetFullPath($AssetRoot)
Write-Host "Scanning: $assetRootFull"

$vst3DestRoot = 'C:\Program Files\Common Files\VST3'
$vst2DestRoot = 'C:\Program Files\VSTPlugins'
$fileFlagsSingle = 'ignoreversion; BeforeInstall: LogBeforeFile; AfterInstall: LogAfterFile'

# --- Collect VST3 candidates ---
$vst3Candidates = @()

$pfVst3 = Join-Path $assetRootFull 'Program Files\Common Files\VST3'
if (Test-Path -LiteralPath $pfVst3) {
    Get-ChildItem -LiteralPath $pfVst3 -Filter '*.vst3' -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
        $relUnderVst3 = Get-RelPath $_.FullName $pfVst3
        $vst3Candidates += [pscustomobject]@{
            Source   = $_.FullName
            DestRel  = $relUnderVst3
            FileName = $_.Name
            Priority = 1
            Origin   = 'Program Files\Common Files\VST3'
        }
    }
}

$pluginsVst3 = Join-Path $assetRootFull 'Plugins\VST3'
if (Test-Path -LiteralPath $pluginsVst3) {
    Get-ChildItem -LiteralPath $pluginsVst3 -Filter '*.vst3' -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
        $relUnderVst3 = Get-RelPath $_.FullName $pluginsVst3
        $vst3Candidates += [pscustomobject]@{
            Source   = $_.FullName
            DestRel  = $relUnderVst3
            FileName = $_.Name
            Priority = 2
            Origin   = 'Plugins\VST3'
        }
    }
}

# Dedup by file name: lower priority number wins
$vst3Selected = @()
$vst3Ignored = @()
$byName = $vst3Candidates | Group-Object -Property FileName
foreach ($g in $byName) {
    $sorted = @($g.Group | Sort-Object Priority, Origin)
    $winner = $sorted[0]
    $vst3Selected += $winner
    if ($sorted.Count -gt 1) {
        foreach ($dup in ($sorted | Select-Object -Skip 1)) {
            $vst3Ignored += $dup
            Write-Host "[DEDUP] keep $($winner.Origin)\$($winner.DestRel); ignore $($dup.Origin)\$($dup.DestRel)"
        }
    }
}

# --- Collect VST2 ---
$vst2Selected = @()
$pfVst2 = Join-Path $assetRootFull 'Program Files\VSTPlugins'
if (Test-Path -LiteralPath $pfVst2) {
    Get-ChildItem -LiteralPath $pfVst2 -Recurse -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Extension -match '^\.(dll|vst)$' } |
        ForEach-Object {
            $rel = Get-RelPath $_.FullName $pfVst2
            $vst2Selected += [pscustomobject]@{
                Source   = $_.FullName
                DestRel  = $rel
                FileName = $_.Name
            }
        }
}

# --- Collect .reg ---
$regSelected = @()
$regDir = Join-Path $assetRootFull (Get-RegDirName)
if (Test-Path -LiteralPath $regDir) {
    Get-ChildItem -LiteralPath $regDir -Filter '*.reg' -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
        $regSelected += [pscustomobject]@{
            Source   = $_.FullName
            FileName = $_.Name
        }
    }
}

# --- Emit files.inc ---
$filesLines = New-Object System.Collections.Generic.List[string]
$filesLines.Add('; Auto-generated by scan_assets.ps1 - do not edit')
$filesLines.Add("; AssetRoot: $assetRootFull")
$filesLines.Add("; Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
$filesLines.Add('')

if ($vst3Selected.Count -eq 0 -and $vst2Selected.Count -eq 0 -and $regSelected.Count -eq 0) {
    $filesLines.Add('; (no plugin/reg assets found)')
}

foreach ($item in ($vst3Selected | Sort-Object DestRel)) {
    $src = Escape-InnoPath $item.Source
    $parent = [System.IO.Path]::GetDirectoryName($item.DestRel)
    if ([string]::IsNullOrWhiteSpace($parent)) {
        $destDir = $vst3DestRoot
    } else {
        $destDir = Join-Path $vst3DestRoot $parent
    }
    $filesLines.Add("Source: `"$src`"; DestDir: `"$destDir`"; Flags: $fileFlagsSingle")
}

foreach ($item in ($vst2Selected | Sort-Object DestRel)) {
    $src = Escape-InnoPath $item.Source
    $parent = [System.IO.Path]::GetDirectoryName($item.DestRel)
    if ([string]::IsNullOrWhiteSpace($parent)) {
        $destDir = $vst2DestRoot
    } else {
        $destDir = Join-Path $vst2DestRoot $parent
    }
    $filesLines.Add("Source: `"$src`"; DestDir: `"$destDir`"; Flags: $fileFlagsSingle")
}

foreach ($item in ($regSelected | Sort-Object FileName)) {
    $src = Escape-InnoPath $item.Source
    $filesLines.Add("Source: `"$src`"; DestDir: {tmp}; Flags: deleteafterinstall")
}

# --- Emit run.inc ---
$runLines = New-Object System.Collections.Generic.List[string]
$runLines.Add('; Auto-generated by scan_assets.ps1 - do not edit')
$runLines.Add('')

if ($regSelected.Count -eq 0) {
    $runLines.Add('; (no .reg files)')
}

foreach ($item in ($regSelected | Sort-Object FileName)) {
    $name = $item.FileName.Replace('"', '')
    $runLines.Add(('Filename: "{win}\regedit.exe"; Parameters: "/s ""{tmp}\' + $name + '"""; Flags: runhidden waituntilterminated'))
}

$utf8Bom = New-Object System.Text.UTF8Encoding $true
[System.IO.File]::WriteAllLines($filesInc, $filesLines.ToArray(), $utf8Bom)
[System.IO.File]::WriteAllLines($runInc, $runLines.ToArray(), $utf8Bom)

Write-Host ''
Write-Host "VST3 selected : $($vst3Selected.Count)"
foreach ($item in ($vst3Selected | Sort-Object DestRel)) {
    Write-Host "  + [$($item.Origin)] $($item.DestRel)"
}
Write-Host "VST3 ignored  : $($vst3Ignored.Count) (dedup)"
Write-Host "VST2 selected : $($vst2Selected.Count)"
foreach ($item in $vst2Selected) {
    Write-Host "  + $($item.DestRel)"
}
Write-Host "REG selected  : $($regSelected.Count)"
foreach ($item in $regSelected) {
    Write-Host "  + $($item.FileName)"
}
Write-Host ''
Write-Host "Wrote: $filesInc"
Write-Host "Wrote: $runInc"